// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsP7b5qHCHxwt5IAOacXawMSHoY3vQ2oI',
    appId: '1:924249676009:web:27a3f6ea644489e7dc3878',
    messagingSenderId: '924249676009',
    projectId: 'instagramclone-d5966',
    authDomain: 'instagramclone-d5966.firebaseapp.com',
    storageBucket: 'instagramclone-d5966.appspot.com',
    measurementId: 'G-0EZP7T2J42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP1kdf7QnfH5eaev1lNpNUgQji14SWoFo',
    appId: '1:924249676009:android:2636582ef8226bf6dc3878',
    messagingSenderId: '924249676009',
    projectId: 'instagramclone-d5966',
    storageBucket: 'instagramclone-d5966.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD35hjU0LAmNQYe4ZwtCiKv0vpVB-9DFU',
    appId: '1:924249676009:ios:5e96ecef2fcc1928dc3878',
    messagingSenderId: '924249676009',
    projectId: 'instagramclone-d5966',
    storageBucket: 'instagramclone-d5966.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD35hjU0LAmNQYe4ZwtCiKv0vpVB-9DFU',
    appId: '1:924249676009:ios:71d8140921cdc695dc3878',
    messagingSenderId: '924249676009',
    projectId: 'instagramclone-d5966',
    storageBucket: 'instagramclone-d5966.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
